In [2]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [3]:
z = torch.zeros(5, 3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


Above, we create a 5x3 matrix filled with zeros, and query its datatype to find out that the zeros are 32-bit floating point numbers, which is the default PyTorch.

What if you wanted integers instead? You can always override the default


In [5]:
i = torch.ones((5, 3), dtype=torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


You can see that we do change the default, the tensor helpfully reports this when printed.

It's common to initialize learning weights randomly, often with a specific seed for the PRNG for reproducibility of results:


In [9]:
torch.manual_seed(1729)
r1 = torch.rand(2, 2)
print("A random tensor:")
print(r1)

r2 = torch.rand(2, 2)
print("\nA different random tensor:")
print(r2) # new values

torch.manual_seed(1729)
r3 = torch.rand(2, 2)
print('\nShould match r1:')
print(r3) # repeats values of r1 because of re-seed

A random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A different random tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

Should match r1:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


PyTorch tensors perform arithmetic operations intuitively. Tensors of similar shapes may be added, multiplied, etc. Operations with scalars are distributed over the tensor

In [25]:
ones = torch.ones(2, 3)
print("ones:\n", ones)

twos = torch.ones(2, 3) * 2 # every element is multiplied by 2
print("twos:\n", twos)

threes = ones + twos        # addition allowed because shapes are similar
print("threes:\n", threes)  # tensors are added element-wise
print(threes.shape)         # this has the same dimension as input tensors


ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
twos:
 tensor([[2., 2., 2.],
        [2., 2., 2.]])
threes:
 tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


Here's small sample pf the mathematical operations available

In [30]:
r = torch.rand(2, 2) - 0.5 * 2  # values between - 1 and 1
print("A random matrix r:")
print(r)


# Common mathematical operations are supported:
print('\nAbsolute value of r:')
print(torch.abs(r))

# ...as are triginimetric functions
print("\nInverse sine of r:")
print(torch.asin(r))

# ...and linear algebra operations likle determinant and singular value decomposition
print("\nDeterminant of r:")
print(torch.det(r))
print("\nSingular value decomposition of r:")
print(torch.svd(r))      

# ...and statistical and aggregate operations:
print('\nAverage tand standard deviation of r:')
print(torch.std_mean(r))
print("\nMaximum value of r:")
print(torch.max(r))

A random matrix r:
tensor([[-0.0549, -0.7641],
        [-0.8021, -0.6673]])

Absolute value of r:
tensor([[0.0549, 0.7641],
        [0.8021, 0.6673]])

Inverse sine of r:
tensor([[-0.0550, -0.8697],
        [-0.9307, -0.7305]])

Determinant of r:
tensor(-0.5762)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.5420, -0.8404],
        [-0.8404,  0.5420]]),
S=tensor([1.2024, 0.4792]),
V=tensor([[ 0.5853, -0.8108],
        [ 0.8108,  0.5853]]))

Average tand standard deviation of r:
(tensor(0.3494), tensor(-0.5721))

Maximum value of r:
tensor(-0.0549)


# Autograd

Automatic Differentiation Engine

Computation as a graph built at run time